import React from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { Building2, Users, MapPin, Boxes, ShieldCheck, LogOut, Plus, RefreshCw, Copy, Check, UserCog, Headphones, Activity, LockKeyhole } from 'lucide-react';
import './saas-admin.css';
import './organization-switcher.css';

const url = import.meta.env.VITE_SAAS_SUPABASE_URL;
const key = import.meta.env.VITE_SAAS_SUPABASE_PUBLISHABLE_KEY;
const supabase = url && key ? createClient(url, key, { auth: { persistSession: true, autoRefreshToken: true } }) : null;

const roleLabels = { owner:'Владелец', admin:'Администратор', manager:'Менеджер', accountant:'Бухгалтер', cashier:'Кассир', chef:'Шеф', auditor:'Аудитор', readonly:'Только просмотр' };
const moduleLabels = { core:'RMS Core', finance:'Финансы', suppliers:'Поставщики', inventory:'Склад', recipes:'Техкарты', hr:'Персонал', reports:'Отчёты', pos:'RMS POS', qr_menu:'QR Menu', loyalty:'Loyalty', ai_analytics:'AI-аналитика' };

function Login({ onLogin }) {
  const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
  async function submit(e){e.preventDefault(); if(!supabase)return setError('Не настроены staging-переменные окружения.'); setBusy(true);setError(''); const {error}=await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(error)setError(error.message); else onLogin();}
  return <main className="login"><section className="login-card"><div className="brand-mark">RMS <span>PRO</span></div><p className="eyebrow">SAAS CONTROL CENTER</p><h1>Управление RMS Cloud</h1><p className="muted">Изолированный staging-контур для организаций, филиалов и доступа сотрудников.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Вход…':'Войти в staging'}</button></form><div className="secure-note"><LockKeyhole size={16}/> Доступ защищён Supabase Auth и RLS</div></section></main>
}

function App(){
 const [session,setSession]=React.useState(null),[loading,setLoading]=React.useState(true),[data,setData]=React.useState({orgs:[],members:[],branches:[],branchMembers:[],modules:[],invites:[],support:[],audit:[]}),[orgId,setOrgId]=React.useState(''),[tab,setTab]=React.useState('overview'),[notice,setNotice]=React.useState(''),[copied,setCopied]=React.useState(''),[showOrganizationCreate,setShowOrganizationCreate]=React.useState(false);
 React.useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 const load=React.useCallback(async()=>{if(!supabase||!session)return;setLoading(true);const tables=['organizations','organization_members','branches','branch_members','organization_modules','organization_invitations','support_access_requests','audit_events'];const queries=await Promise.all(tables.map(t=>supabase.from(t).select('*')));const next={orgs:queries[0].data||[],members:queries[1].data||[],branches:queries[2].data||[],branchMembers:queries[3].data||[],modules:queries[4].data||[],invites:queries[5].data||[],support:queries[6].data||[],audit:queries[7].data||[]};setData(next);setOrgId(v=>next.orgs.some(o=>o.id===v)?v:(next.orgs[0]?.id||''));setLoading(false)},[session]);
 React.useEffect(()=>{load()},[load]);
 async function rpc(name,args){setNotice('');const {data,error}=await supabase.rpc(name,args);if(error){setNotice('Ошибка: '+error.message);throw error}setNotice('Изменение сохранено');await load();return data}
 if(loading&&!session)return <div className="splash">RMS PRO <span>STAGING</span></div>; if(!session)return <Login onLogin={load}/>;
 const org=data.orgs.find(x=>x.id===orgId);const scoped=x=>x.filter(v=>v.organization_id===orgId);const nav=[['overview','Обзор',Building2],['branches','Филиалы',MapPin],['members','Сотрудники',Users],['invites','Приглашения',UserCog],['modules','Модули',Boxes],['support','Поддержка',Headphones],['audit','Аудит',Activity]];
 return <div className="shell"><aside><div className="logo">RMS <b>PRO</b><small>SAAS STAGING</small></div><select className="org-select" value={orgId} onChange={e=>setOrgId(e.target.value)}>{data.orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><div className="aside-foot"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Выйти</button></div></aside><main className="content"><header><div><p className="eyebrow">RMS CLOUD / STAGING</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1><p>{org?.name||'Организация ещё не создана'}</p></div><button className="icon-btn" onClick={load} aria-label="Обновить данные"><RefreshCw size={18}/></button></header><OrganizationSwitcher orgs={data.orgs} orgId={orgId} onChange={setOrgId} onCreate={()=>setShowOrganizationCreate(v=>!v)}/>{showOrganizationCreate&&<OrganizationCreateForm rpc={rpc} onClose={()=>setShowOrganizationCreate(false)}/>} {notice&&<div className={notice.startsWith('Ошибка')?'toast error':'toast'}>{notice}</div>}{!org?<EmptyOrganization rpc={rpc}/>:<Panel tab={tab} org={org} data={data} scoped={scoped} rpc={rpc} copied={copied} setCopied={setCopied}/>}</main></div>
}

function OrganizationSwitcher({orgs,orgId,onChange,onCreate}){return <section className="organization-switcher"><label><span>Организация</span><select value={orgId} onChange={e=>onChange(e.target.value)} aria-label="Выбор организации">{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><div className="organization-switcher-actions"><span>{orgs.length} {orgs.length===1?'организация':'организации'}</span><button className="primary small" onClick={onCreate}><Plus size={16}/>Новая</button></div></section>}
function OrganizationCreateForm({rpc,onClose,showCancel=true}){const [name,setName]=React.useState(''),[slug,setSlug]=React.useState(''),[busy,setBusy]=React.useState(false);async function submit(){if(!name.trim()||!slug.trim())return;setBusy(true);try{await rpc('create_organization',{p_name:name.trim(),p_slug:slug.trim().toLowerCase()});onClose()}catch{}finally{setBusy(false)}}return <section className="organization-create form-card"><div><strong>Новая организация</strong><small>Будет создана только в RMS SaaS Staging.</small></div><input placeholder="Название компании" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="slug-company" value={slug} onChange={e=>setSlug(e.target.value)}/><button className="primary" disabled={busy||!name.trim()||!slug.trim()} onClick={submit}>{busy?'Создаю…':'Создать организацию'}</button>{showCancel&&<button className="secondary-button" onClick={onClose}>Отмена</button>}</section>}
function EmptyOrganization({rpc}){return <section className="empty"><Building2 size={40}/><h2>Создайте первую тестовую организацию</h2><p>Она будет создана только в RMS SaaS Staging.</p><OrganizationCreateForm rpc={rpc} onClose={()=>{}} showCancel={false}/></section>}

function Panel({tab,org,data,scoped,rpc,copied,setCopied}){
 const branches=scoped(data.branches),members=scoped(data.members),invites=scoped(data.invites),modules=scoped(data.modules),support=scoped(data.support),audit=scoped(data.audit);
 if(tab==='overview')return <><div className="stats"><Stat label="Филиалы" value={branches.filter(x=>x.status==='active').length}/><Stat label="Сотрудники" value={members.filter(x=>x.is_active).length}/><Stat label="Активные модули" value={modules.filter(x=>x.is_enabled).length}/><Stat label="Ожидают приглашения" value={invites.filter(x=>x.status==='pending').length}/></div><section className="card"><h2>Контур организации</h2><dl><div><dt>ID</dt><dd>{org.id}</dd></div><div><dt>Slug</dt><dd>{org.slug}</dd></div><div><dt>Статус</dt><dd><Badge value={org.status}/></dd></div></dl></section></>;
 if(tab==='branches')return <Branches rows={branches} org={org} rpc={rpc}/>;
 if(tab==='members')return <Members rows={members} branches={branches} branchMembers={scoped(data.branchMembers||[])} org={org} rpc={rpc}/>;
 if(tab==='invites')return <Invites rows={invites} branches={branches} org={org} rpc={rpc} copied={copied} setCopied={setCopied}/>;
 if(tab==='modules')return <Modules rows={modules} org={org} rpc={rpc}/>;
 if(tab==='support')return <Support rows={support} org={org} rpc={rpc}/>;
 return <Table rows={audit} cols={[['created_at','Дата'],['action','Действие'],['entity_table','Объект'],['actor_user_id','Пользователь']]}/>;
}
const Stat=({label,value})=><div className="stat"><span>{label}</span><strong>{value}</strong></div>; const Badge=({value})=><span className={'badge '+value}>{value}</span>;
function Table({rows,cols,actions}){return <section className="card table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}{actions&&<th/>}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{cols.map(([k])=><td key={k}>{k.includes('_at')&&r[k]?new Date(r[k]).toLocaleString('ru-RU'):k==='status'?<Badge value={r[k]}/>:String(r[k]??'—')}</td>)}{actions&&<td>{actions(r)}</td>}</tr>):<tr><td colSpan={cols.length+1} className="empty-row">Данных пока нет</td></tr>}</tbody></table></section>}
function Branches({rows,org,rpc}){const [open,setOpen]=React.useState(false),[f,setF]=React.useState({code:'',name:'',timezone:'Asia/Baku'});return <><Toolbar title="Филиалы организации" action={()=>setOpen(!open)}/>{open&&<div className="form-card"><input placeholder="Код, например BC1" onChange={e=>setF({...f,code:e.target.value})}/><input placeholder="Название" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.timezone} onChange={e=>setF({...f,timezone:e.target.value})}/><button className="primary" onClick={()=>rpc('create_branch',{p_organization_id:org.id,p_code:f.code,p_name:f.name,p_timezone:f.timezone})}>Сохранить</button></div>}<Table rows={rows} cols={[['code','Код'],['name','Название'],['timezone','Часовой пояс'],['status','Статус']]} actions={r=>r.status==='active'&&<button className="danger" onClick={()=>rpc('deactivate_branch',{p_branch_id:r.id})}>Деактивировать</button>}/></>}
function Members({rows,org,rpc}){return <Table rows={rows} cols={[['user_id','User ID'],['role','Роль'],['is_active','Активен'],['joined_at','Добавлен']]} actions={r=><div className="row-actions"><select value={r.role} onChange={e=>rpc('set_organization_member_role',{p_organization_id:org.id,p_user_id:r.user_id,p_role:e.target.value})}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{r.role!=='owner'&&<button className="danger" onClick={()=>rpc('set_organization_member_active',{p_organization_id:org.id,p_user_id:r.user_id,p_is_active:!r.is_active})}>{r.is_active?'Отключить':'Включить'}</button>}</div>}/>} 
function Invites({rows,branches,org,rpc,copied,setCopied}){const [open,setOpen]=React.useState(false),[token,setToken]=React.useState(''),[f,setF]=React.useState({email:'',role:'manager',branchIds:[]});async function create(){const d=await rpc('create_member_invitation',{p_organization_id:org.id,p_email:f.email,p_role:f.role,p_branch_ids:f.branchIds,p_valid_hours:72});const row=Array.isArray(d)?d[0]:d;setToken(row?.invitation_token||'')}return <><Toolbar title="Одноразовые приглашения" action={()=>setOpen(!open)}/>{open&&<div className="form-card"><input type="email" placeholder="employee@company.az" onChange={e=>setF({...f,email:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}>{Object.entries(roleLabels).filter(([v])=>!['owner'].includes(v)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="checks">{branches.filter(b=>b.status==='active').map(b=><label key={b.id}><input type="checkbox" onChange={e=>setF({...f,branchIds:e.target.checked?[...f.branchIds,b.id]:f.branchIds.filter(x=>x!==b.id)})}/>{b.name}</label>)}</div><button className="primary" onClick={create}>Создать приглашение</button>{token&&<div className="token"><code>{token}</code><button onClick={()=>{navigator.clipboard.writeText(token);setCopied(token)}}>{copied===token?<Check/>:<Copy/>}</button><small>Токен показывается один раз. Передайте его сотруднику безопасным способом.</small></div>}</div>}<Table rows={rows} cols={[['email','Email'],['role','Роль'],['status','Статус'],['expires_at','Действует до']]} actions={r=>r.status==='pending'&&<button className="danger" onClick={()=>rpc('revoke_member_invitation',{p_invitation_id:r.id})}>Отозвать</button>}/></>}
function Modules({rows,org,rpc}){return <><div className="section-note"><ShieldCheck/>Изменение модулей разрешено только RMS Super Admin с MFA (AAL2).</div><div className="module-grid">{Object.entries(moduleLabels).map(([code,label])=>{const row=rows.find(x=>x.module_code===code);return <div className="module" key={code}><div><Boxes/><strong>{label}</strong><small>{code}</small></div><button className={row?.is_enabled?'toggle on':'toggle'} onClick={()=>rpc('set_organization_module',{p_organization_id:org.id,p_module_code:code,p_is_enabled:!row?.is_enabled,p_settings:row?.settings||{}})}><span/></button></div>})}</div></>}
function Support({rows,org,rpc}){const [reason,setReason]=React.useState('');return <><div className="form-card"><textarea placeholder="Причина обращения (минимум 10 символов)" value={reason} onChange={e=>setReason(e.target.value)}/><button className="primary" onClick={()=>rpc('create_support_access_request',{p_organization_id:org.id,p_reason:reason,p_duration_hours:4})}>Запросить доступ на 4 часа</button></div><Table rows={rows} cols={[['created_at','Создан'],['reason','Причина'],['status','Статус'],['expires_at','Истекает']]}/></>}
function Toolbar({title,action}){return <div className="toolbar"><h2>{title}</h2><button className="primary small" onClick={action}><Plus size={16}/>Добавить</button></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
